### ISSUE TITLE
Groovy reloading fails when executed from TimerTask

### ISSUE THREAD

**Issue by robymus** [jmarranz/relproxy#6]
I have run into a little problem, when a class is reloaded and is invoked from a timer task, it fails with "java.lang.ClassCastException: test.Ticker cannot be cast to test.Ticker"

I have created a minimal test project to reproduce this, you can check it at: https://github.com/robymus/gproxy-timer-reload-issue

Basically I create a class and interface, as in the documentations, and invoke a method from a timer task regularly. When the class is reloaded, an exception is thrown, but only if there is an other method with at least 2 arguments (myMethod in the test) called from the first method invoked (tick), and the arguments are changed (when the body of myMethod is changed, there is no problem).

```groovy
package test
class Ticker implements ITicker {
 void tick() {
  myMethod(0, null) // changing 0 to 1 triggers exception
 }
 void myMethod(int x, String job) {
 }
}
```

Maybe my groovy environment setup is flawed, I tried to follow the description and everything works correctly when outside of a timer, but it's still a possibility.

I get the following exception trace from my test project:

```java.lang.reflect.UndeclaredThrowableException
        at com.sun.proxy.$Proxy7.tick(Unknown Source)
        at test.ITicker$tick.call(Unknown Source)
        at test.Start.run(Start.groovy:40)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at com.innowhere.relproxy.impl.GenericProxyInvocationHandler.invoke(GenericProxyInvocationHandler.java:63)
        ... 5 more
Caused by: java.lang.ClassCastException: test.Ticker cannot be cast to test.Ticker
        at test.Ticker$myMethod.callCurrent(Unknown Source)
        at test.Ticker.tick(Ticker.groovy:4)
        ... 10 more
```

**Comment by jmarranz** [comment]
GProxy was created to improve Groovy - Java integration, that is, using Groovy in a Java environment, usually a Java framework.

The principal GProxy use case is to register a Groovy listener in a Java registry.

In your case the problem seems the interface ITicker, this interface should be a pure Java interface loaded by the Java infrastructure part of the Java "framework" used by your Groovy code, but in your case ITicker is loaded by Groovy class loader.

**Comment by robymus** [comment]
Thanks, that clears it up. Please consider this issue a "non-issue", as I was  trying to GProxy in a way it was not intended to be used.
